[package]
name = "place_setbyte"
version = "0.1.0"
edition = "2021"

[dependencies]
users = { workspace = true }
place_lib = { workspace = true }
place_constants = { workspace = true }
chacha20poly1305 = { workspace = true }
