#[package]
#name = "place_init"
#version = "0.1.0"
#edition = "2021"

#[dependencies]
#config = "0.15.4"

[workspace]
members = ["backend", "frontend/*"]
resolver = "2"

[workspace.dependencies]
place_constants = { path = "constants" }
